version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=testdb
      - DB_USER=testuser
      - DB_PASSWORD=testpass
      - NYLAS_BASE_URL=http://15.204.46.122:8056
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - nylas-network

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - nylas-network

networks:
  nylas-network:
    driver: bridge

volumes:
  postgres-data: